### ISSUE TITLE
"NLTK tokenizers are missing."

### ISSUE THREAD

**Issue by raj6996** [agermanidis/videodigest#3]
https://github.com/agermanidis/videodigest
I installed it 64 bit Windows 10 pro.
but not worked.
also installed this ubuntu virtualbox. getting this error.

yl@yl-VirtualBox:~$ videodigest -i /media/sf_I/xm/xm.mp4 -s /media/sf_I/xm/xm.srt -L English -o rip.mp4
 
Traceback (most recent call last):
  File "/home/yl/.local/bin/videodigest", line 108, in <module>
    language=args.language)
  File "/home/yl/.local/bin/videodigest", line 75, in find_summary_regions
    summary = summarize(srt_file, summarizer, n_sentences, language)
  File "/home/yl/.local/bin/videodigest", line 60, in summarize
    parser = PlaintextParser.from_string(srt_to_doc(srt_file), Tokenizer(language))
  File "/home/yl/.local/lib/python2.7/site-packages/sumy/nlp/tokenizers.py", line 67, in __init__
    self._sentence_tokenizer = self._get_sentence_tokenizer(tokenizer_language)
  File "/home/yl/.local/lib/python2.7/site-packages/sumy/nlp/tokenizers.py", line 82, in _get_sentence_tokenizer
    "NLTK tokenizers are missing. Download them by following command: "
LookupError: NLTK tokenizers are missing. Download them by following command: python -c "import nltk; nltk.download('punkt')"

how to fix this?

**Comment by srichakradhar** [comment]
You have the answer in the last line:
Just run `python -c "import nltk; nltk.download('punkt')`
